Added camera properties to scene table
uwblueprint/cdc-backend pull request #35
Opened 2021-02-24 02:41 UTC by drbalar

- create script
- mock data
- models
- tornado validation
- tornado sample data

2021-02-24 05:00 UTC, jaydhulia requested changes

2021-02-24 05:09 UTC, drbalar commented on app/library/api_schemas.py
> +        "camera_properties": {"type": "object"},
yep. I did not know if validation was possible to that level.. would it be like `camera_properties.position: {type ...}`?

2021-02-24 05:41 UTC, jaydhulia commented on app/library/api_schemas.py
> +        "camera_properties": {"type": "object"},
Yup, you should be able to do nested validation. As an example:
```
admin_scene_post_handler_schema = {
    "type": "object",
    "properties": {
        "name": {"type": "string", "pattern": r"^[a-zA-Z _-]{,50}$"},
        "background_id": {"type": "integer"},
        "camera_properties": {
                    "type": "object",
                    "properties": {
                            "position": {"type": "array", "items": {"type": "number"}}
                             <Other properties within camera_properties here>
                     },
                     "required": ["position", <other properties>]
         },
    },
    "required": [
        "name",
        "background_id",
        "camera_properties",
    ],
}
```

2021-02-26 02:49 UTC, ahmedhamodi submitted a review, later dismissed

2021-02-26 08:42 UTC, jaydhulia submitted a review, later dismissed
LGTM

2021-02-26 15:20 UTC, ahmedhamodi approved these changes

2021-02-26 15:24 UTC, merged